include:
  - backend/docker-compose.yml
  - frontend/docker-compose.yml
services:
  e2e_test:
    image: cypress/included
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e
    depends_on:
      - frontend
      - backend
    entrypoint: cypress run --e2e --config baseUrl=${CYPRESS_BASE_URL}