include:
  - backend/docker-compose.yml
  - frontend/docker-compose.yml
services:
  e2e_tests:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - BACKEND_URL=${REACT_APP_API_ENDPOINT-:PLEASE_SET_REACT_APP_API_ENDPOINT}
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.config.js:/app/cypress.config.js
    depends_on:
      - frontend
      - backend
    entrypoint: yarn cypress run --e2e --config baseUrl=${CYPRESS_BASE_URL:-PLEASE_SET_CYPRESS_BASE_URL}
