version: '3'
services:
  backend:
    environment:
      - PORT=${BACKEND_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=http://postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
  postgres:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
