on:
  push:
    branches:
      - main
name: End-to-End Tests # TODO: Perhaps optimize by non docker-compose build. Post Run of below caching action is quite slow.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Docker Compose Build
        run: docker compose --env-file e2e.env build
      - name: Run End-to-End Tests
        run: docker compose --env-file e2e.env run e2e_tests
