on: [push] # TODO: Better not run this on every push but for debug purpose, leave it for now.
name: End-to-End Tests
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Docker Compose Build
        run: docker compose --env-file e2e.env build
      - name: Run End-to-End Tests
        run: docker compose --env-file e2e.env run e2e_tests
